version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - baknine-network-swarm
    depends_on:
      - frontend
      - backend
      - database
  database :
    image: postgres:latest
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 500M
      restart_policy:
        condition: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=projet
      - POSTGRES_PASSWORD=nouhaila
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - baknine-network-swarm

  backend:
    image: nouhabk23/backend-image-final:1.0.0
    environment:
     SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/projet
     SPRING_DATASOURCE_USERNAME: postgres
     SPRING_DATASOURCE_PASSWORD: nouhaila
     SPRINNG_JPA_HIBERNATE_DDL_AUTO: update
    ports:
    - "8080:8080"
    depends_on:
    - database
    networks:
    - baknine-network-swarm
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1.0" 
          memory: 1G
      restart_policy:
        condition: on-failure
        delay: 5s
    
  frontend:
    image: nouhabk23/frontend-image-final:1.0.0
    ports:
      - "3000:80"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 512M 
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - baknine-network-swarm
    depends_on:
      - backend
networks:
  baknine-network-swarm:
    external: true

volumes:
  db_data:
    driver: local
  traefik-certificates:
    driver: local